### ISSUE TITLE
Can't edit Leetcode files.

### ISSUE THREAD

**Issue by daljeetv** [chishui/terminal-leetcode#16]
When I press 'e' to edit or 'n' to create new file- program quits with following stacktrace:

<img width="1006" alt="screen shot 2017-05-18 at 2 54 10 pm" src="https://cloud.githubusercontent.com/assets/14968486/26224995/efe02f7a-3bd9-11e7-97c5-bb65db19a808.png">

**Comment by chishui** [comment]
It's a bug, I'll fix it later. Try add path of your directory where you want to save your code to in config.cfg, then I think you should workaround this bug. Thanks~

**Comment by daljeetv** [comment]
Thanks adding this worked:
`path=~/leetcode`
