### ISSUE TITLE
In java view, failed to submit code

### ISSUE THREAD

**Issue by superchaoran** [chishui/terminal-leetcode#17]
![image](https://cloud.githubusercontent.com/assets/7088689/26432217/ef667f5c-40ae-11e7-9c3f-bb366b50d681.png)
![image](https://cloud.githubusercontent.com/assets/7088689/26432230/05d013a2-40af-11e7-9a61-a0891f98be5d.png)
![image](https://cloud.githubusercontent.com/assets/7088689/26432248/36a543c6-40af-11e7-899f-2daae5754161.png)
checked submission log, the code sent was the default template, not the one user typed

**Comment by chishui** [comment]
How do you write your config.cfg?

**Comment by superchaoran** [comment]
Pasting config down here:
Chaorans-MacBook-Pro:~ chaoranwang$ cat  ~/.config/leetcode/config.cfg

[leetcode]
username=superchaoran
password=blablabla
language=Java
ext=java # file extention
path=~/program/leetcode # code file directory

**Comment by chishui** [comment]
It's weird, my configuration is the same in 'language' and 'ext' with yours. Did you use pip to install the package or compile the source code?

**Comment by superchaoran** [comment]
@chishui I cloned the code into my workspace and compile it

**Comment by chishui** [comment]
Could you update the code and compile it again?

**Comment by superchaoran** [comment]
My local version is on the master branch and up to date. The last commit was by you on Sunday. :)

**Comment by superchaoran** [comment]
Another friend of mine also experiences the same issue. I am trying to reinstall and see how.

**Comment by chishui** [comment]
OK, I'll investigate this issue.

**Comment by superchaoran** [comment]
i just uninstalled and using the pip method.
looks like its submitting the template instead of saved code using c++.
though i use java in config:

Chaorans-MacBook-Pro:terminal-leetcode chaoranwang$ cat ~/.config/leetcode/config.cfg
[leetcode]
username=superchaoran
password=blablabla
language=Java
ext=java # file extention
path=~/program/leetcode # code file directory
![image](https://cloud.githubusercontent.com/assets/7088689/26468136/36124fda-414a-11e7-903c-eda1cfb03f27.png)

Thx, if you need any help. I can provide you with log details. @chishui

**Comment by chishui** [comment]
Yeah, there is a bug in last pip package, it is fixed in code but I haven't update pip package, so the source code should use java code.

**Comment by superchaoran** [comment]
gotcha. redownloaded the source code and compile. gives this:
![image](https://cloud.githubusercontent.com/assets/7088689/26468433/447b25e6-414b-11e7-8614-f1821f86571e.png)

**Comment by chishui** [comment]
So if you press 'e' to edit code you can see the code you input before?

**Comment by superchaoran** [comment]
Exactly, pressing e has no problem shown previously wrotten code.

**Comment by chishui** [comment]
Sent you an invitation on gtalk

**Comment by superchaoran** [comment]
try superchaoran@gmail.com, i didn't receive your invitation :)

**Comment by chishui** [comment]
Google hangouts doesn't have a function to resend invitation..
Could you help me add some log in 'submit_code' to see if the filepath and code from the file are correct?

**Comment by superchaoran** [comment]
Added you on hangout. Trying to log it.

**Comment by superchaoran** [comment]
@chishui thx, problem solved. turns out we can't include # in config, will take # as path 👍

**Comment by chishui** [comment]
Great, thx
