### ISSUE TITLE
[Improvement] Some improvement to show the return status

### ISSUE THREAD

**Issue by ray-x** [chishui/terminal-leetcode#18]
Hi, ChiShui
I have a patch that can show/log the failed case and ETL failed case.  It is ugly but seems to be useful. 

[showFailedCases.diff.zip](https://github.com/chishui/terminal-leetcode/files/1034723/showFailedCases.diff.zip)

**Comment by chishui** [comment]
Hi,
I'm working on a new way to display the result of submission, let's wait until the new release to see if it meets your need.

Thanks

**Comment by ray-x** [comment]
Cool! Thanks!
