### ISSUE TITLE
Program crashed

### ISSUE THREAD

**Issue by fengzhyuan** [chishui/terminal-leetcode#20]
reproduce:
run `leetcode` and login, the system popped out a warning regarding to SSL, then jumped to problem list

select an arbitrary problem and press `enter`, popped out the following error:  
`Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()   Exclusive Time of Functions
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/leetcode/terminal.py", line 209, in run_retrieve_detail
    ret = self.leetcode.retrieve_detail(data)                                                         
  File "/usr/local/lib/python2.7/dist-packages/leetcode/leetcode.py", line 127, in retrieve_detail    
    for child in a:
TypeError: 'NoneType' object is not iterable`

![capture](https://user-images.githubusercontent.com/12440564/28991171-613c2060-7939-11e7-960d-3dad3f0d2510.PNG)

**Comment by chishui** [comment]
I can reproduce this issue, working on this.

**Comment by chishui** [comment]
Fixed. Please update your application.

**Comment by fengzhyuan** [comment]
Thanks for your quick response! But I found another problem, after I created the `.config` file under `.config/leetcode` folder and restarted the program, it indicates that I was logged in but also shows `have solved 0/577 problems`, there're also some gray problems that could not be edit, (I have subscribed the LC service), any idea? thanks in advance! (osx system)

**Comment by chishui** [comment]
the config file should be named as "config.cfg", please follow instruction in README
