### ISSUE TITLE
Can not edit code

### ISSUE THREAD

**Issue by GameBurning** [chishui/terminal-leetcode#26]
When I press "e", it has not effect and won't enter vim mode. I have set the ext and path in config file.

**Comment by chishui** [comment]
Yes, it's a bug, will be working on it. Thanks for reporting.

**Comment by chishui** [comment]
Are you running "leetcode" inside tmux?

**Comment by GameBurning** [comment]
No, just normal mode. Tried both Terminal and iTerm on MacOS.

**Comment by chishui** [comment]
Did you set tmux_support in your config.cfg?

**Comment by GameBurning** [comment]
No

**Comment by chishui** [comment]
Could you try to run command `export EDITOR=vi` before run leetcode again?
