### ISSUE TITLE
Handle Error Code 13: Output Limit Exceeded 

### ISSUE THREAD

**Issue by jhshi** [chishui/terminal-leetcode#27]
Sample response JSON:

{"lang": "python", "total_testcases": 37, "user_id": 293601, "status_code": 13, "compare_result": "1111111111111111111111111111111111100", "status_runtime": "N/A", "state": "SUCCESS", "total_correct": 35, "run_success": false, "judge_type": "large", "std_output": "a super long output", "question_id": "207"}

**Comment by chishui** [comment]
Fixed it!
