### ISSUE TITLE
Handle Error Code 12: Memory Limit Exceeded

### ISSUE THREAD

**Issue by jhshi** [chishui/terminal-leetcode#29]
Sample response:

{"lang": "python", "total_testcases": 47, "user_id": 293601, "status_code": 12, "compare_result": "11111111111111111111111111111111111111111111111", "status_runtime": "N/A", "state": "SUCCESS", "total_correct": 47, "run_success": false, "judge_type": "large", "std_output": "", "runtime_error": "", "last_testcase": "[\"a super long input\"]", "question_id": "361"}

![image](https://user-images.githubusercontent.com/1173734/30007268-00f70f96-90c0-11e7-94cd-8f7aa0c1c68c.png)

**Comment by chishui** [comment]
Fixed it
