### ISSUE TITLE
stuck on the 'loading ...' page

### ISSUE THREAD

**Issue by luckystarufo** [chishui/terminal-leetcode#3]
Hi, thanks for your work!
When I set up the things, I get stuck on the 'loading...' page (not the 'login ...') and cannot see the questions. Any idea to work this out?

**Comment by chishui** [comment]
Hi, 
it's because Leetcode.com changed it's pages' html format. I'm working on it. Will fix it ASAP.
Thanks,

**Comment by luckystarufo** [comment]
Oh, thanks so much. It is a so cool project!

**Comment by chishui** [comment]
Have already fixed it.
Please use `pip install --upgrade terminal-leetcode` to upgrade your package to update your repository.
Thanks

**Comment by luckystarufo** [comment]
Works great ! Thanks !
