### ISSUE TITLE
get Request Fail when load quiz

### ISSUE THREAD

**Issue by goalong** [chishui/terminal-leetcode#37]
error message is:
![image](https://user-images.githubusercontent.com/7417284/34025325-2eed5a5c-e18a-11e7-9d45-3e1c199bda16.png)

**Comment by chishui** [comment]
Because Leetcode website has changed their website content. We can't get the content in old way. I'm trying to figure out a new way. Thanks

**Comment by goalong** [comment]
I should say thanks, great work, this project is very helpful.

**Comment by chishui** [comment]
Thanks, that means a lot to me!

**Comment by chishui** [comment]
Fixed
