### ISSUE TITLE
error when login

### ISSUE THREAD

**Issue by mqliang** [chishui/terminal-leetcode#39]
I set my user name and password in `~/.config/leetcode` as :
```
[leetcode]
username=<username>
password=<password>
```
But the login of terminal-leetcode is failed.  

I also tried to read your source code and use the following python script to test the leetcode login API, also failed. Seems the leetcode API has already been changed. Any ideas? 

```
import requests

headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, sdch',
    'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2',
    'Connection': 'keep-alive',
    'Host': 'leetcode.com',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36',
    'Referer': 'https://leetcode.com/accounts/login/',
}

BASE_URL = 'https://leetcode.com'
LOGIN_URL = BASE_URL + '/accounts/login/'
SESSION_URL = BASE_URL + '/session'

r = requests.post(LOGIN_URL, data={'login': '<username>', 'password': '<password>', 'remember': 'on'}, headers = headers)

print(r.status_code, r)
```

**Comment by mqliang** [comment]
cc @zhujinghui

**Comment by pkm2019** [comment]
Same here.. Even I am running into an issue. Please check. Thanks.

**Comment by chishui** [comment]
Leetcode has restricted their login by adding Google captcha which is, so far as I know, not easy to bypass. I made changes by using Chrome cookies in this program and use those cookies to all requests. It works, but you need to login your account from chrome browser if you have never done that before.
