### ISSUE TITLE
some content is missing

### ISSUE THREAD

**Issue by praenubilus** [chishui/terminal-leetcode#4]
For some questions, some of the content is missing. e.g. in question 415, the length of num1 and num2 is missing on line 5. But it should be < 5100.

My environment:
OSX 10.11
default terminal
python 2.7.12

![screen shot 2016-10-16 at 19 35 23](https://cloud.githubusercontent.com/assets/547418/19421826/e4cdb04e-93d7-11e6-80d0-ddf0a40f0aee.png)

**Comment by chishui** [comment]
I guess you are using the old version, because it works well on my computer. You could update to the latest code and try the new version. Thanks!

**Comment by praenubilus** [comment]
I don't believe so since I installed through pip. Is there a way to get the version number?

**Comment by chishui** [comment]
Yes, it should be. I tried on my laptop, osx 10.12, terminal.app. I installed the program inside virtualenv (for a completely new environment), it works fine. So could you reinstall the program? This problem should be fixed in 0.0.7, because 0.0.7 switched to lxml to parse html.

**Comment by praenubilus** [comment]
tried on both git clone and pip, still the same issue.

**Comment by chishui** [comment]
In terminal type `which leetcode` to see if you're using the right program

**Comment by praenubilus** [comment]
/usr/local/bin/leetcode, all python package are up to date.
