### ISSUE TITLE
Support submitting Python3 code

### ISSUE THREAD

**Issue by robotechdy** [chishui/terminal-leetcode#43]
I suggest adding a line like `'Python3': 'python3',` into the `LANG_MAPPING` [link](https://github.com/chishui/terminal-leetcode/blob/master/leetcode/helper/common.py#L7) to enable Python3 support.
After that, we can enable Python3 in `.config/leetcode/config.cfg` by assigning `language=Python3`

**Comment by chishui** [comment]
Added in 0.0.20.
