### ISSUE TITLE
leetcode CLI submit code to the wrong id

### ISSUE THREAD

**Issue by robotechdy** [chishui/terminal-leetcode#44]
Sometimes, I found `leetcode submit --id xxx` submit the code to a wrong question id

For example, I have a source code file saved in `~/leetcode/986.`. Then, I run `leetcode submit --id 986` to submit the code, and I found that the code is submitted to question `949`. This issue also happened to other question ids like: `708`, `509` etc

The LeetCode site is doing some id-remapping tricks to break external CLI? Or, this is just a bug?

**Comment by chishui** [comment]
I fixed it in 0.0.20. LeetCode website does have a frondEnd id to backEnd id mapping.

**Comment by hoyden** [comment]
@chishui How could I get the id mapping? It is messed up again.
