### ISSUE TITLE
pip based installation 

### ISSUE THREAD

**Issue by vyas45** [chishui/terminal-leetcode#6]
I installed using pip : pip install terminal-leetcode

When I try to run the program , I get the following error:

I use python 2.7 and have the dependencies furnished. 

> → leetcode
> Traceback (most recent call last):
>   File "/usr/local/bin/leetcode", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/leetcode/__main__.py", line 6, in main
>     init_logger()
>   File "/usr/local/lib/python2.7/site-packages/leetcode/log.py", line 13, in init_logger
>     logging.basicConfig(level=logging.info)
>   File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1558, in basicConfig
>     root.setLevel(level)
>   File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1143, in setLevel
>     self.level = _checkLevel(level)
>   File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 185, in _checkLevel
>     raise TypeError("Level not an integer or a valid string: %r" % level)
> TypeError: Level not an integer or a valid string: <function info at 0x107c3c9b0>
>

**Comment by chishui** [comment]
It seems like a bug, I'll fix it ASAP. Thanks

**Comment by chishui** [comment]
Fixed it! Please use pip to update to new version. Thanks.

**Comment by vyas45** [comment]
Awesome stuff !  Thanks a lot. Also, great work. This is very useful.
