### ISSUE TITLE
Unable to open quiz detail view

### ISSUE THREAD

**Issue by rohansapre** [chishui/terminal-leetcode#7]
Used the pip install terminal-leetcode. Using a 64bit Ubuntu 16.04 machine.
Login works correctly, but when I try to enter any of the quiz detail view, I get either this error:

![terminal_leetcode_error](https://cloud.githubusercontent.com/assets/6986727/25552964/681c0f14-2c75-11e7-884b-1da2714f785c.png)

I double checked all the dependencies as well, please let me know if I missed out on something.

**Comment by chishui** [comment]
Leetcode has changed its way to generate web content, I'm working on it, but need to take some time.

**Comment by chishui** [comment]
Fix it. You can use pip install --upgrade terminal-leetcode to install update. Thanks.

**Comment by rohansapre** [comment]
Great! Thanks.
