### ISSUE TITLE
Submit Python Code

### ISSUE THREAD

**Issue by jhshi** [chishui/terminal-leetcode#8]
Very nice application! Really appreciated.

One question about submitting Python code. I set "language=Python" in config.cfg and was able to see sample code in Python. However, when I tried to submit Python code, it seems Leetcode interprets it as Cpp code and complains about various compilation errors.

After digging into the source code, I found the "lang" field of the request body is hard-coded into "cpp". Any reasons why is this? And can it be configured through the configuration file?

Thanks again.

**Comment by chishui** [comment]
That should be a bug and it should use the data in configuration file. I'll be working on it. If you have already had a solution for this bug, you're welcome to submit your code.

Thanks

**Comment by jhshi** [comment]
Do you know where to find the list of acceptable "lang" field of the request body? Is it full language name (e.g., Python) or just file extension (e.g., py)?

**Comment by chishui** [comment]
I tried to submit code in all languages on leetcode's website to get "lang" fields and the relationship between language name and its "lang" field is shown below:
C++, cpp
C#, csharp
Python, python
Java, java
C, c
Javascript, javascript
...

**Comment by jhshi** [comment]
Thanks! I'm working on it, will send a pull request soon.

**Comment by chishui** [comment]
Thanks, the pull request has been approved and merged.
